export const STUDENTS = [{
  "name": "Aleta",
  "attendence": 78,
  "score": 97
}, {
  "name": "Weber",
  "attendence": 70,
  "score": 35
}, {
  "name": "Renate",
  "attendence": 78,
  "score": 45
}, {
  "name": "Arman",
  "attendence": 81,
  "score": 98
}, {
  "name": "Fleur",
  "attendence": 47,
  "score": 38
}, {
  "name": "Koenraad",
  "attendence": 78,
  "score": 40
}, {
  "name": "Melisande",
  "attendence": 54,
  "score": 77
}, {
  "name": "Brana",
  "attendence": 75,
  "score": 89
}, {
  "name": "Adelaida",
  "attendence": 72,
  "score": 40
}, {
  "name": "Nolan",
  "attendence": 61,
  "score": 43
}, {
  "name": "Kahaleel",
  "attendence": 37,
  "score": 59
}, {
  "name": "Sumner",
  "attendence": 76,
  "score": 78
}, {
  "name": "Vivyanne",
  "attendence": 52,
  "score": 93
}, {
  "name": "Conny",
  "attendence": 77,
  "score": 41
}, {
  "name": "Irwin",
  "attendence": 37,
  "score": 68
}, {
  "name": "Cassius",
  "attendence": 99,
  "score": 70
}, {
  "name": "Agatha",
  "attendence": 52,
  "score": 41
}, {
  "name": "Florencia",
  "attendence": 40,
  "score": 86
}, {
  "name": "Sande",
  "attendence": 65,
  "score": 87
}, {
  "name": "Witty",
  "attendence": 74,
  "score": 67
}, {
  "name": "Barde",
  "attendence": 80,
  "score": 72
}, {
  "name": "Elga",
  "attendence": 37,
  "score": 86
}, {
  "name": "Ashlie",
  "attendence": 86,
  "score": 94
}, {
  "name": "Robinett",
  "attendence": 73,
  "score": 78
}, {
  "name": "King",
  "attendence": 81,
  "score": 79
}, {
  "name": "Nanette",
  "attendence": 62,
  "score": 48
}, {
  "name": "Dag",
  "attendence": 84,
  "score": 98
}, {
  "name": "Curcio",
  "attendence": 87,
  "score": 85
}, {
  "name": "Ediva",
  "attendence": 99,
  "score": 72
}, {
  "name": "Felice",
  "attendence": 65,
  "score": 59
}, {
  "name": "Carri",
  "attendence": 87,
  "score": 33
}, {
  "name": "Lockwood",
  "attendence": 53,
  "score": 81
}, {
  "name": "Bethany",
  "attendence": 82,
  "score": 52
}, {
  "name": "Cordie",
  "attendence": 58,
  "score": 37
}, {
  "name": "Lydon",
  "attendence": 36,
  "score": 47
}, {
  "name": "Johna",
  "attendence": 84,
  "score": 80
}, {
  "name": "Anestassia",
  "attendence": 38,
  "score": 73
}, {
  "name": "Merrilee",
  "attendence": 63,
  "score": 57
}, {
  "name": "Cissy",
  "attendence": 83,
  "score": 43
}, {
  "name": "Staci",
  "attendence": 40,
  "score": 67
}, {
  "name": "Clarinda",
  "attendence": 40,
  "score": 39
}, {
  "name": "Editha",
  "attendence": 61,
  "score": 78
}, {
  "name": "Pren",
  "attendence": 42,
  "score": 85
}, {
  "name": "Arabelle",
  "attendence": 99,
  "score": 39
}, {
  "name": "Elsworth",
  "attendence": 73,
  "score": 85
}, {
  "name": "Merell",
  "attendence": 77,
  "score": 36
}, {
  "name": "Cathe",
  "attendence": 98,
  "score": 85
}, {
  "name": "Bonnie",
  "attendence": 80,
  "score": 94
}, {
  "name": "Trstram",
  "attendence": 64,
  "score": 77
}, {
  "name": "Darius",
  "attendence": 100,
  "score": 61
}, {
  "name": "Barnebas",
  "attendence": 98,
  "score": 94
}, {
  "name": "Nerita",
  "attendence": 79,
  "score": 62
}, {
  "name": "Amaleta",
  "attendence": 39,
  "score": 52
}, {
  "name": "Stephi",
  "attendence": 81,
  "score": 45
}, {
  "name": "Elsy",
  "attendence": 67,
  "score": 95
}, {
  "name": "Lindy",
  "attendence": 51,
  "score": 70
}, {
  "name": "Onfroi",
  "attendence": 34,
  "score": 56
}, {
  "name": "Aldon",
  "attendence": 89,
  "score": 77
}, {
  "name": "Loy",
  "attendence": 92,
  "score": 34
}, {
  "name": "Porty",
  "attendence": 37,
  "score": 33
}, {
  "name": "Gordan",
  "attendence": 91,
  "score": 65
}, {
  "name": "Bret",
  "attendence": 75,
  "score": 78
}, {
  "name": "Malachi",
  "attendence": 56,
  "score": 82
}, {
  "name": "Tabbitha",
  "attendence": 76,
  "score": 56
}, {
  "name": "Jordon",
  "attendence": 67,
  "score": 35
}, {
  "name": "Iggy",
  "attendence": 92,
  "score": 74
}, {
  "name": "Alec",
  "attendence": 72,
  "score": 97
}, {
  "name": "Kevyn",
  "attendence": 73,
  "score": 75
}, {
  "name": "Otho",
  "attendence": 77,
  "score": 80
}, {
  "name": "Samara",
  "attendence": 49,
  "score": 62
}, {
  "name": "Aubine",
  "attendence": 58,
  "score": 51
}, {
  "name": "Lorelei",
  "attendence": 82,
  "score": 66
}, {
  "name": "Dosi",
  "attendence": 84,
  "score": 53
}, {
  "name": "Chrissie",
  "attendence": 72,
  "score": 67
}, {
  "name": "Patricia",
  "attendence": 87,
  "score": 57
}, {
  "name": "Ileane",
  "attendence": 65,
  "score": 34
}, {
  "name": "Benton",
  "attendence": 91,
  "score": 46
}, {
  "name": "Dylan",
  "attendence": 50,
  "score": 66
}, {
  "name": "Cleopatra",
  "attendence": 60,
  "score": 51
}, {
  "name": "Rakel",
  "attendence": 80,
  "score": 98
}, {
  "name": "Jayson",
  "attendence": 78,
  "score": 68
}, {
  "name": "Jaynell",
  "attendence": 100,
  "score": 48
}, {
  "name": "Sauveur",
  "attendence": 78,
  "score": 68
}, {
  "name": "Emery",
  "attendence": 90,
  "score": 54
}, {
  "name": "Corissa",
  "attendence": 51,
  "score": 79
}, {
  "name": "Kenny",
  "attendence": 64,
  "score": 98
}, {
  "name": "Barbabra",
  "attendence": 60,
  "score": 84
}, {
  "name": "Bobbie",
  "attendence": 86,
  "score": 84
}, {
  "name": "Kerstin",
  "attendence": 70,
  "score": 63
}, {
  "name": "Chevy",
  "attendence": 68,
  "score": 70
}, {
  "name": "Natala",
  "attendence": 88,
  "score": 100
}, {
  "name": "Halimeda",
  "attendence": 58,
  "score": 98
}, {
  "name": "Sterne",
  "attendence": 85,
  "score": 72
}, {
  "name": "Adorne",
  "attendence": 86,
  "score": 46
}, {
  "name": "Sterne",
  "attendence": 63,
  "score": 39
}, {
  "name": "Maurizio",
  "attendence": 97,
  "score": 91
}, {
  "name": "Karen",
  "attendence": 45,
  "score": 45
}, {
  "name": "Netty",
  "attendence": 82,
  "score": 59
}, {
  "name": "Dante",
  "attendence": 71,
  "score": 68
}, {
  "name": "Betteanne",
  "attendence": 45,
  "score": 58
}];